### PR TITLE
eth/abi: allow parsing numerics from string inputs

### LINKED ISSUE #110: comparison of String with Integer failed
I encode a uint256 with a string. eg "10000000000000000000000" from json.

and there is no convert cause this error.

### PR DESCRIPTION
**Pull request by q9f**
fix #110

### CODE REVIEW

**Comment by pynixwang** [comment]
hex number not work

```
"00000000000000000000000000000000000000000000021e19e0c9bab2400000".to_i
=> 21

```

**Comment by pynixwang** [comment]
hex number not work

```
"00000000000000000000000000000000000000000000021e19e0c9bab2400000".to_i
=> 21

```

**Comment by q9f** [comment]
> hex number not work
> 
> ```
> "00000000000000000000000000000000000000000000021e19e0c9bab2400000".to_i
> => 21
> ```

You need to preprocess the JSON in this case. There is no way to know if a string is binary, octal, decimal, or hexadecimal.

**Comment by pynixwang** [comment]
decimal is enough.

I found you have hex string in test, so I have a try. do you run you test?

**Comment by unixneo** [comment]
> I found you have hex string in test, so I have a try. do you run you test?

```ruby
test = "00000000000000000000000000000000000000000000021e19e0c9bab2400000".hex
=> 10000000000000000000000
test.to_s(16)
=> "21e19e0c9bab2400000"
```

**Comment by kurotaky** [comment]
For hexadecimal numbers, the argument to_i() must be 16.

```ruby
irb(main):005:0> "00000000000000000000000000000000000000000000021e19e0c9bab2400000".to_i(16)
=> 10000000000000000000000
```

However, it is difficult to distinguish octal, decimal, or hexadecimal in the following pattern... 😢 

```ruby
irb(main):016:0> '000255'.to_i(8)
=> 173
irb(main):017:0> '000255'.to_i(10)
=> 255
irb(main):018:0> '000255'.to_i(16)
=> 597
```

**Comment by pynixwang** [comment]
decimal string is enough for most cases.

**Pull request merged**
